humanoid_target:
  ros__parameters:
    taskFile: ""
    referenceFile: ""
    urdfFile: ""
    urdfFileOrigin: ""
    gaitCommandFile: ""

normal_controller:
  ros__parameters:
    taskFile: ""
    referenceFile: ""
    urdfFile: ""
    urdfFileOrigin: ""
    gaitCommandFile: ""

cheat_controller:
  ros__parameters:
    taskFile: ""
    referenceFile: ""
    urdfFile: ""
    urdfFileOrigin: ""
    gaitCommandFile: ""

joy_controller:
  ros__parameters:
    taskFile: ""
    referenceFile: ""
    urdfFile: ""
    urdfFileOrigin: ""
    gaitCommandFile: ""
